"""
Simulation API Routes
Step 2: Zep Entity Reading & Filtering, OASIS Simulation Preparation & Running (Fully Automated)
"""

import traceback
from flask import request, jsonify

from .. import simulation_bp
from ..simulation import (
    _with_profile_truth,
    _validate_prepare_controls,
    _check_simulation_prepared,
)
from .. import limiter
from ...config import Config
from ...services.zep_entity_reader import ZepEntityReader
from ...services.oasis_profile_generator import OasisProfileGenerator
from ...services.simulation_manager import SimulationManager, SimulationStatus
from ...services.claim_boundary import (
    fictional_profile_disclosure,
    synthetic_output_disclosure,
)
from ...utils.logger import get_logger
from ...utils.input_policy import InputPolicyError, PREPARE_ENTITY_MAX
from ...models.project import ProjectManager

logger = get_logger('askthepeople.api.simulation')



# P0 path-escape fix (audit §5 P0). The platform identifier is a request-
# controlled value; it MUST be parsed as a strict enum and resolved to a
# fixed filename. Do NOT interpolate request text into a filename.
ALLOWED_PLATFORMS = {
    "reddit": "reddit_simulation.db",
    "twitter": "twitter_simulation.db",
}



@simulation_bp.route('/create', methods=['POST'])
@limiter.limit(Config.RATELIMIT_LLM_MEDIUM)
def create_simulation():
    """
    Create new simulation
    
    Note: Parameters like max_rounds are intelligently generated by LLM, no manual setting needed
    
    Request (JSON):
        {
            "project_id": "proj_xxxx",      // Required
            "graph_id": "atp_xxxx",    // Optional, retrieved from project if not provided
            "enable_twitter": true,          // Optional, default true
            "enable_reddit": true            // Optional, default true
        }
    
    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "project_id": "proj_xxxx",
                "graph_id": "atp_xxxx",
                "status": "created",
                "enable_twitter": true,
                "enable_reddit": true,
                "created_at": "2025-12-01T10:00:00"
            }
        }
    """
    try:
        data = request.get_json() or {}
        
        project_id = data.get('project_id')
        if not project_id:
            return jsonify({
                "success": False,
                "error": "Please provide project_id"
            }), 400
        
        project = ProjectManager.get_project(project_id)
        if not project:
            return jsonify({
                "success": False,
                "error": f"Project does not exist: {project_id}"
            }), 404
        
        graph_id = data.get('graph_id') or project.graph_id
        if not graph_id:
            return jsonify({
                "success": False,
                "error": "Graph not yet built for the project, please call /api/graph/build first"
            }), 400
        
        manager = SimulationManager()
        state = manager.create_simulation(
            project_id=project_id,
            graph_id=graph_id,
            enable_twitter=data.get('enable_twitter', True),
            enable_reddit=data.get('enable_reddit', True),
        )
        
        return jsonify({
            "success": True,
            "data": state.to_dict()
        })
        
    except Exception as e:
        logger.error(f"Failed to create simulation: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500

@simulation_bp.route('/prepare', methods=['POST'])
@limiter.limit(Config.RATELIMIT_LLM_HEAVY)
def prepare_simulation():
    """
    Prepare simulation environment (asynchronous task, LLM intelligently generates all parameters)
    
    This is a time-consuming operation, the interface will immediately return task_id,
    Use GET /api/simulation/prepare/status to query progress
    
    Features:
    - Automatically detect completed preparation to avoid duplicate generation
    - If already prepared, return existing results directly
    - Support force regeneration (force_regenerate=true)
    
    Steps:
    1. Check for existing completed preparation work
    2. Read and filter entities from Zep graph
    3. Generate OASIS Agent Profile for each entity (with retry mechanism)
    4. LLM intelligently generates simulation configuration (with retry mechanism)
    5. Save configuration files and preset scripts
    
    Request (JSON):
        {
            "simulation_id": "sim_xxxx",                   // Required, Simulation ID
            "entity_types": ["Student", "PublicFigure"],  // Optional, specify entity types
            "use_llm_for_profiles": true,                 // Optional, whether to use LLM for generating personas
            "parallel_profile_count": 5,                  // Optional, number of parallel persona generations, default 5
            "force_regenerate": false                     // Optional, force regeneration, default false
        }
    
    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "task_id": "task_xxxx",           // Returned for new task
                "status": "preparing|ready",
                "message": "Preparation task started|Existing preparation work found",
                "already_prepared": true|false    // Whether preparation is complete
            }
        }
    """
    import os
    from ...models.task import TaskManager
    from ...config import Config
    
    try:
        data = request.get_json() or {}
        
        simulation_id = data.get('simulation_id')
        if not simulation_id:
            return jsonify({
                "success": False,
                "error": "Please provide simulation_id"
            }), 400

        try:
            prepare_controls = _validate_prepare_controls(data)
        except InputPolicyError as exc:
            return jsonify({
                "success": False,
                "error": exc.code,
                "message": exc.message,
            }), 400
        
        manager = SimulationManager()
        state = manager.get_simulation(simulation_id)
        
        if not state:
            return jsonify({
                "success": False,
                "error": f"Simulation does not exist: {simulation_id}"
            }), 404
        
        # Check if force regenerate
        force_regenerate = prepare_controls["force_regenerate"]
        logger.info(f"Start processing /prepare request: simulation_id={simulation_id}, force_regenerate={force_regenerate}")
        
        # Check if already prepared (avoid duplicate generation)
        if not force_regenerate:
            logger.debug(f"Checking if simulation {simulation_id} is prepared...")
            is_prepared, prepare_info = _check_simulation_prepared(simulation_id)
            logger.debug(f"Check result: is_prepared={is_prepared}, prepare_info={prepare_info}")
            if is_prepared:
                logger.info(f"Simulation {simulation_id} Preparation complete, skipping duplicate generation")
                return jsonify({
                    "success": True,
                    "data": {
                        "simulation_id": simulation_id,
                        "status": "ready",
                        "message": "Existing preparation work found, no need to regenerate",
                        "already_prepared": True,
                        "prepare_info": prepare_info
                    }
                })
            else:
                logger.info(f"Simulation {simulation_id} Preparation not complete, starting preparation task")
        
        # Get required info from project
        project = ProjectManager.get_project(state.project_id)
        if not project:
            return jsonify({
                "success": False,
                "error": f"Project does not exist: {state.project_id}"
            }), 404
        
        # Get simulation requirements
        simulation_requirement = project.simulation_requirement or ""
        if not simulation_requirement:
            return jsonify({
                "success": False,
                "error": "Project missing simulation requirement description (simulation_requirement)"
            }), 400
        
        # Get document text
        document_text = ProjectManager.get_extracted_text(state.project_id) or ""
        
        entity_types_list = prepare_controls["entity_types"]
        use_llm_for_profiles = prepare_controls["use_llm_for_profiles"]
        parallel_profile_count = prepare_controls["parallel_profile_count"]
        use_archetypes = prepare_controls["use_archetypes"]
        archetype_count = prepare_controls["archetype_count"]
        expansion_factor = prepare_controls["expansion_factor"]
        
        # ========== Synchronously get entity count (before background task start) ==========
        # This allows the frontend to get the expected total Agent count immediately after calling prepare
        try:
            logger.info(f"Synchronously get entity count: graph_id={state.graph_id}")
            reader = ZepEntityReader()
            # Fast read entities (count only, no edge info needed)
            filtered_preview = reader.filter_defined_entities(
                graph_id=state.graph_id,
                defined_entity_types=entity_types_list,
                enrich_with_edges=False  # Speed up by not retrieving edge info
            )
            if filtered_preview.filtered_count > PREPARE_ENTITY_MAX:
                return jsonify({
                    "success": False,
                    "error": "entity_count_out_of_range",
                    "message": (
                        "The selected graph contains "
                        f"{filtered_preview.filtered_count} profile entities; "
                        f"the maximum is {PREPARE_ENTITY_MAX}."
                    ),
                }), 400
            # Save entity count to state (for immediate frontend retrieval)
            state.entities_count = filtered_preview.filtered_count
            state.entity_types = list(filtered_preview.entity_types)
            logger.info(f"Expected entity count: {filtered_preview.filtered_count}, types: {filtered_preview.entity_types}")
        except Exception as e:
            logger.warning(f"Failed to synchronously get entity count (will retry in background task): {e}")
            # Failure does not affect subsequent steps as the background task will retry
        
        # Create background task. An optional Idempotency-Key header dedupes
        # double-submits (network retry, double-click): if a prepare task for
        # this key is already in flight, its existing task_id is returned and
        # no second task is enqueued (ADR-0003 idempotency keys).
        idempotency_key = request.headers.get("Idempotency-Key") or None
        task_manager = TaskManager()

        # If a prepare for this key is already in flight, hand back that
        # task_id and skip enqueueing a duplicate worker job. NOTE: there is a
        # benign TOCTOU window between this find and create_task below — two
        # concurrent requests with the same key could both see None here and
        # both reach the enqueue step. create_task also dedupes under its lock,
        # so they would share one task_id, but both would enqueue a worker job.
        # This is safe today because the web runs as a single worker (Procfile
        # --workers 1); the multi-worker case is the gate 2/4 blocker. Moving
        # the dedup fully behind a single atomic create-or-return call is part
        # of that work.
        already_in_flight_task_id = None
        if idempotency_key:
            already_in_flight_task_id = task_manager.find_in_flight_by_idempotency_key(
                idempotency_key
            )

        task_id = already_in_flight_task_id or task_manager.create_task(
            task_type="simulation_prepare",
            metadata={
                "simulation_id": simulation_id,
                "project_id": state.project_id
            },
            idempotency_key=idempotency_key,
        )

        # Update simulation state (including pre-fetched entity count)
        state.status = SimulationStatus.PREPARING
        manager._save_simulation_state(state)

        # Only enqueue the worker job for a genuinely new task. A deduped
        # (already-in-flight) submission returns the existing task_id and
        # does not start a second preparation run.
        if not already_in_flight_task_id:
            from ...tasks.simulation_tasks import prepare_simulation_task

            prepare_simulation_task.delay(
                simulation_id=simulation_id,
                task_id=task_id,
                entity_types=entity_types_list,
                use_llm_for_profiles=use_llm_for_profiles,
                parallel_profile_count=parallel_profile_count,
                use_archetypes=use_archetypes,
                archetype_count=archetype_count,
                expansion_factor=expansion_factor,
                document_text=document_text,
            )

        response = jsonify({
            "success": True,
            "data": {
                "simulation_id": simulation_id,
                "task_id": task_id,
                "status": "preparing",
                "message": "Preparation task enqueued. Poll /api/simulation/prepare/status for progress.",
                "already_prepared": False,
                "expected_entities_count": state.entities_count,  # Expected total Agents
                "entity_types": state.entity_types  # Entity types list
            }
        })
        return response, 202, {"Location": f"/api/jobs/{task_id}"}
        
    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 404
        
    except Exception as e:
        logger.error(f"Failed to start preparation task: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500

@simulation_bp.route('/prepare/status', methods=['POST'])
def get_prepare_status():
    """
    Query preparation task progress
    
    Supports two query methods:
    1. Query progress of an ongoing task via task_id
    2. Check for completed preparation work via simulation_id
    
    Request (JSON):
        {
            "task_id": "task_xxxx",          // Optional, task_id returned by prepare
            "simulation_id": "sim_xxxx"      // Optional, simulation ID (for checking completed preparation)
        }
    
    Returns:
        {
            "success": true,
            "data": {
                "task_id": "task_xxxx",
                "status": "processing|completed|ready",
                "progress": 45,
                "message": "...",
                "already_prepared": true|false,  // Whether preparation is complete
                "prepare_info": {...}            // Detailed information when preparation is complete
            }
        }
    """
    from ...models.task import TaskManager
    
    try:
        data = request.get_json() or {}
        
        task_id = data.get('task_id')
        simulation_id = data.get('simulation_id')
        
        # If simulation_id is provided, check if already prepared
        if simulation_id:
            is_prepared, prepare_info = _check_simulation_prepared(simulation_id)
            if is_prepared:
                return jsonify({
                    "success": True,
                    "data": {
                        "simulation_id": simulation_id,
                        "status": "ready",
                        "progress": 100,
                        "message": "Existing preparation work found",
                        "already_prepared": True,
                        "prepare_info": prepare_info
                    }
                })
        
        # If no task_id, return error
        if not task_id:
            if simulation_id:
                # With simulation_id but not prepared yet
                return jsonify({
                    "success": True,
                    "data": {
                        "simulation_id": simulation_id,
                        "status": "not_started",
                        "progress": 0,
                        "message": "Preparation not started, please call /api/simulation/prepare to start",
                        "already_prepared": False
                    }
                })
            return jsonify({
                "success": False,
                "error": "Please provide task_id or simulation_id"
            }), 400
        
        task_manager = TaskManager()
        task = task_manager.get_task(task_id)
        
        if not task:
            # Task does not exist, but if simulation_id is provided, check for completed preparation
            if simulation_id:
                is_prepared, prepare_info = _check_simulation_prepared(simulation_id)
                if is_prepared:
                    return jsonify({
                        "success": True,
                        "data": {
                            "simulation_id": simulation_id,
                            "task_id": task_id,
                            "status": "ready",
                            "progress": 100,
                            "message": "Task completed (preparation work already exists)",
                            "already_prepared": True,
                            "prepare_info": prepare_info
                        }
                    })
            
            return jsonify({
                "success": False,
                "error": f"Task does not exist: {task_id}"
            }), 404
        
        task_dict = task.to_public_dict()
        task_dict["already_prepared"] = False
        
        return jsonify({
            "success": True,
            "data": task_dict
        })
        
    except Exception as e:
        logger.error(f"Failed to query task status: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e)
        }), 500

@simulation_bp.route('/generate-profiles', methods=['POST'])
@limiter.limit(Config.RATELIMIT_LLM_MEDIUM)
def generate_profiles():
    """
    Generate OASIS Agent Profile directly from graph (without creating simulation)
    
    Request (JSON):
        {
            "graph_id": "atp_xxxx",           // Required
            "entity_types": ["Student"],      // Optional
            "use_llm": true,                  // Optional
            "platform": "reddit"              // Optional
        }
    """
    try:
        data = request.get_json() or {}
        
        graph_id = data.get('graph_id')
        if not graph_id:
            return jsonify({
                "success": False,
                "error": "Please provide graph_id"
            }), 400
        
        entity_types = data.get('entity_types')
        use_llm = data.get('use_llm', True)
        platform = data.get('platform', 'reddit')
        
        reader = ZepEntityReader()
        filtered = reader.filter_defined_entities(
            graph_id=graph_id,
            defined_entity_types=entity_types,
            enrich_with_edges=True
        )
        
        if filtered.filtered_count == 0:
            return jsonify({
                "success": False,
                "error": "No matching entities found"
            }), 400
        
        generator = OasisProfileGenerator()
        profiles = generator.generate_profiles_from_entities(
            entities=filtered.entities,
            use_llm=use_llm
        )
        
        if platform == "reddit":
            profiles_data = [p.to_reddit_format() for p in profiles]
        elif platform == "twitter":
            profiles_data = [p.to_twitter_format() for p in profiles]
        else:
            profiles_data = [p.to_dict() for p in profiles]
        profiles_data = _with_profile_truth(profiles_data)
        
        return jsonify({
            "success": True,
            "data": {
                "platform": platform,
                "entity_types": list(filtered.entity_types),
                "count": len(profiles_data),
                "profiles": profiles_data,
                **fictional_profile_disclosure(),
            },
            "disclosure": synthetic_output_disclosure(),
        })
        
    except Exception as e:
        logger.error(f"Failed to generate profile: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500

@simulation_bp.route('/<simulation_id>/preflight', methods=['GET'])
def get_simulation_preflight(simulation_id: str):
    try:
        manager = SimulationManager()
        preflight = manager.get_preflight(simulation_id)
        if not preflight:
            return jsonify({
                "success": False,
                "error": "preflight.json does not exist, please complete /prepare first"
            }), 404
        return jsonify({
            "success": True,
            "data": preflight
        })
    except Exception as e:
        logger.error(f"Failed to get preflight: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500

@simulation_bp.route('/<simulation_id>/diagnostics', methods=['GET'])
def get_simulation_diagnostics(simulation_id: str):
    try:
        manager = SimulationManager()
        diagnostics = manager.get_diagnostics(simulation_id)
        return jsonify({
            "success": True,
            "data": diagnostics
        })
    except Exception as e:
        logger.error(f"Failed to get diagnostics: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500
