import os
import re

def translate_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Dictionary for string replacements (Chinese -> English)
    translations = {
        '# 此脚本读取配置文件中的参数来执行模拟，实现全程自动化': '# This script reads parameters from the config file to execute the simulation, achieving full automation.',
        'python run_twitter_simulation.py --config /path/to/simulation_config.json --no-wait  # 完成后立即关闭': 'python run_twitter_simulation.py --config /path/to/simulation_config.json --no-wait  # Close immediately after completion',
        '# 加载项目根目录的 .env 文件（包含 LLM_API_KEY 等配置）': '# Load .env file from the project root (contains LLM_API_KEY and other configurations)',
        '\"\"\"自定义格式化器，将 Unicode 转义序列转换为可读字符\"\"\"': '\"\"\"Custom formatter to convert Unicode escape sequences to readable characters\"\"\"',
        '# 过滤掉包含 max_tokens 警告的日志': '# Filter out logs containing max_tokens warning',
        '测试Profile格式生成是否符合OASIS要求': 'Test if Profile format generation meets OASIS requirements',
        '验证：': 'Verification:',
        '1. Twitter Profile生成CSV格式': '1. Twitter Profile generates CSV format',
        '2. Reddit Profile生成JSON详细格式': '2. Reddit Profile generates detailed JSON format',
        '# 添加项目路径': '# Add project path',
        '\"\"\"测试Profile格式\"\"\"': '\"\"\"Test Profile format\"\"\"',
        'print(\"OASIS Profile格式测试\")': 'print(\"OASIS Profile format test\")',
        '# 创建测试Profile数据': '# Create test Profile data',
        '# 使用临时目录': '# Use temporary directory',
        '# 测试Twitter CSV格式': '# Test Twitter CSV format',
        'print(\"\\n1. 测试Twitter Profile (CSV格式)\")': 'print(\"\\n1. Test Twitter Profile (CSV format)\")',
        '# 读取并验证CSV': '# Read and verify CSV',
        'print(f\"   文件: {twitter_path}\")': 'print(f\"   File: {twitter_path}\")',
        'print(f\"   行数: {len(rows)}\")': 'print(f\"   Line count: {len(rows)}\")',
        'print(f\"   表头: {list(rows[0].keys())}\")': 'print(f\"   Header: {list(rows[0].keys())}\")',
        'print(f\"\\n   示例数据 (第1行):\")': 'print(f\"\\n   Example data (Line 1):\")',
        '# 验证必需字段': '# Verify required fields',
        'print(f\"\\n   [错误] 缺少字段: {missing}\")': 'print(f\"\\n   [Error] Missing field: {missing}\")',
        'print(f\"\\n   [通过] 所有必需字段都存在\")': 'print(f\"\\n   [Pass] All required fields exist\")',
        '# 测试Reddit JSON格式': '# Test Reddit JSON format',
        'print(\"\\n2. 测试Reddit Profile (JSON详细格式)\")': 'print(\"\\n2. Test Reddit Profile (detailed JSON format)\")',
        '# 读取并验证JSON': '# Read and verify JSON',
        'print(f\"   条目数: {len(reddit_data)}\")': 'print(f\"   Entry count: {len(reddit_data)}\")',
        'print(f\"   字段: {list(reddit_data[0].keys())}\")': 'print(f\"   Fields: {list(reddit_data[0].keys())}\")',
        'print(f\"\\n   示例数据 (第1条):\")': 'print(f\"\\n   Example data (Entry 1):\")',
        '# 验证详细格式字段': '# Verify detailed format fields',
        'print(f\"\\n   [错误] 缺少必需字段: {missing}\")': 'print(f\"\\n   [Error] Missing required field: {missing}\")',
        'print(f\"\\n   [通过] 所有必需字段都存在\")': 'print(f\"\\n   [Pass] All required fields exist\")',
        'print(f\"   [信息] 可选字段: {present_optional}\")': 'print(f\"   [Info] Optional fields: {present_optional}\")',
        'print(\"测试完成!\")': 'print(\"Test completed!\")',
        '\"\"\"显示OASIS期望的格式\"\"\"': '\"\"\"Display expected OASIS format\"\"\"',
        'print(\"OASIS 期望的Profile格式参考\")': 'print(\"Reference for expected OASIS Profile format\")',
        'print(\"\\n1. Twitter Profile (CSV格式)\")': 'print(\"\\n1. Twitter Profile (CSV format)\")',
        'print(\"\\n2. Reddit Profile (JSON详细格式)\")': 'print(\"\\n2. Reddit Profile (detailed JSON format)\")',
        'OASIS Twitter模拟预设脚本': 'OASIS Twitter Simulation Preset Script',
        'OASIS Reddit模拟预设脚本': 'OASIS Reddit Simulation Preset Script',
        '此脚本读取配置文件中的参数来执行模拟，实现全程自动化': 'This script reads parameters from the config file to execute the simulation, achieving full automation.',
        '# 同时运行Twitter和Reddit模拟，读取相同的配置文件': '# Runs Twitter and Reddit simulations simultaneously, reading from the same configuration file.',
        '# 功能特性:': '# Features:',
        '# - 双平台（Twitter + Reddit）并行模拟': '# - Dual-platform (Twitter + Reddit) parallel simulation',
        '# - 完成模拟后不立即关闭环境，进入等待命令模式': '# - Enters command-wait mode instead of closing environment immediately after simulation',
        '# - 支持通过IPC接收Interview命令': '# - Supports receiving Interview commands via IPC',
        '# - 支持单个Agent采访和批量采访': '# - Supports single Agent interview and batch interviews',
        '# - 支持远程关闭环境命令': '# - Supports remote environment closure commands',
        '# 使用方式:': '# Usage:',
        '# 日志结构:': '# Log Structure:',
        '# Twitter 平台动作日志': '# Twitter platform action logs',
        '# Reddit 平台动作日志': '# Reddit platform action logs',
        '# 主模拟进程日志': '# Main simulation process log',
        '# 运行状态（API 查询用）': '# Running state (for API queries)',
        '# 解决 Windows 编码问题：在所有 import 之前设置 UTF-8 编码': '# Resolve Windows encoding issues: set UTF-8 encoding before any imports',
        '# 这是为了修复 OASIS 第三方库读取文件时未指定编码的问题': '# This fixes issues where OASIS third-party libraries read files without specifying encoding',
        '# 设置 Python 默认 I/O 编码为 UTF-8': '# Set Python default I/O encoding to UTF-8',
        '# 这会影响所有未指定编码的 open() 调用': '# This affects all open() calls that do not specify an encoding',
        '# 重新配置标准输出流为 UTF-8（解决控制台中文乱码）': '# Reconfigure standard output stream to UTF-8 (resolve console garbled characters)',
        '# 强制设置默认编码（影响 open() 函数的默认编码）': '# Force set default encoding (affects default encoding of open() function)',
        '# 注意：这需要在 Python 启动时就设置，运行时设置可能不生效': '# Note: This needs to be set at Python startup, may not take effect if set during runtime',
        '# 所以我们还需要 monkey-patch 内置的 open 函数': '# So we also need to monkey-patch the built-in open function',
        '包装 open() 函数，对于文本模式默认使用 UTF-8 编码': 'Wrap open() function, default to UTF-8 encoding for text mode',
        '这可以修复第三方库（如 OASIS）读取文件时未指定编码的问题': 'This fixes issues where third-party libraries (like OASIS) read files without specifying encoding',
        '# 只对文本模式（非二进制）且未指定编码的情况设置默认编码': '# Set default encoding only for text mode (non-binary) where encoding is not specified',
        '# 全局变量：用于信号处理': '# Global variables: used for signal handling',
        '# 添加 backend 目录到路径': '# Add backend directory to path',
        '# 脚本固定位于 backend/scripts/ 目录': '# Script is fixed in backend/scripts/ directory',
        '已加载环境配置': 'Loaded environment config',
        '过滤掉 camel-ai 关于 max_tokens 的警告（我们故意不设置 max_tokens，让模型自行决定）': 'Filter out camel-ai warnings about max_tokens (we deliberately don\'t set max_tokens, let the model decide)',
        '# 过滤掉包含 max_tokens 警告的日志': '# Filter out logs containing max_tokens warning',
        '# 在模块加载时立即添加过滤器，确保在 camel 代码执行前生效': '# Add filter immediately on module load to ensure it takes effect before camel code execution',
        '禁用 OASIS 库的详细日志输出': 'Disable detailed logging from OASIS library',
        'OASIS 的日志太冗余（记录每个 agent 的观察和动作），我们使用自己的 action_logger': 'OASIS logs are too redundant (logging observations and actions for every agent), we use our own action_logger',
        '# 禁用 OASIS 的所有日志器': '# Disable all OASIS loggers',
        '# 只记录严重错误': '# Only log critical errors',
        '初始化模拟的日志配置': 'Initialize simulation logging configuration',
        '模拟目录路径': 'Path to simulation directory',
        '# 禁用 OASIS 的详细日志': '# Disable detailed OASIS logs',
        '# 清理旧的 log 目录（如果存在）': '# Clean up old log directory if it exists',
        '错误: 缺少依赖': 'Error: Missing dependency',
        '请先安装: pip install oasis-ai camel-ai': 'Please install: pip install oasis-ai camel-ai',
        '# Twitter可用动作（不包含INTERVIEW，INTERVIEW只能通过ManualAction手动触发）': '# Available Twitter actions (excluding INTERVIEW, which is triggered manually via ManualAction)',
        '# Reddit可用动作（不包含INTERVIEW，INTERVIEW只能通过ManualAction手动触发）': '# Available Reddit actions (excluding INTERVIEW, which is triggered manually via ManualAction)',
        '# IPC相关常量': '# IPC-related constants',
        '\"\"\"命令类型常量\"\"\"': '\"\"\"Command type constants\"\"\"',
        '双平台IPC命令处理器': 'Dual-platform IPC command handler',
        '管理两个平台的环境，处理Interview命令': 'Manages environments for both platforms and processes Interview commands',
        '# 确保目录存在': '# Ensure directories exist',
        '\"\"\"更新环境状态\"\"\"': '\"\"\"Update environment status\"\"\"',
        '\"\"\"轮询获取待处理命令\"\"\"': '\"\"\"Poll for pending commands\"\"\"',
        '# 获取命令文件（按时间排序）': '# Get command files (sorted by time)',
        '\"\"\"发送响应\"\"\"': '\"\"\"Send response\"\"\"',
        '# 删除命令文件': '# Delete command file',
        '获取指定平台的环境和agent_graph': 'Get environment and agent_graph for the specified platform',
        '平台名称 (\"twitter\" 或 \"reddit\")': 'Platform name (\"twitter\" or \"reddit\")',
        '(env, agent_graph, platform_name) 或 (None, None, None)': '(env, agent_graph, platform_name) or (None, None, None)',
        '在单个平台上执行Interview': 'Execute Interview on a single platform',
        '包含结果的字典，或包含error的字典': 'Dictionary containing the result, or dictionary containing the error',
        '处理单个Agent采访命令': 'Process single agent interview command',
        '命令ID': 'Command ID',
        '采访问题': 'Interview question',
        '指定平台（可选）': 'Specified platform (optional)',
        '- \"twitter\": 只采访Twitter平台': '- \"twitter\": Only interview on Twitter',
        '- \"reddit\": 只采访Reddit平台': '- \"reddit\": Only interview on Reddit',
        '- None/不指定: 同时采访两个平台，返回整合结果': '- None/Not specified: Interview on both platforms and return combined results',
        'True 表示成功，False 表示失败': 'True for success, False for failure',
        '# 如果指定了平台，只采访该平台': '# If platform is specified, only interview on that platform',
        'Interview完成:': 'Interview completed:',
        '# 未指定平台：同时采访两个平台': '# Unspecified platform: interview both simultaneously',
        '没有可用的模拟环境': 'No available simulation environment',
        '# 并行采访两个平台': '# Interview both platforms in parallel',
        '开始双平台并行Interview:': 'Starting dual-platform parallel Interview:',
        '# 并行执行': '# Execute in parallel',
        '成功平台数=': 'successful platforms=',
        '未知错误': 'Unknown error',
        'Interview失败:': 'Interview failed:',
        '所有平台都失败': 'all platforms failed',
        '处理批量采访命令': 'Process batch interview command',
        '默认平台（可被每个interview项覆盖）': 'Default platform (can be overridden by each interview item)',
        '- None/不指定: 每个Agent同时采访两个平台': '- None/Not specified: Interview both platforms for each agent',
        '# 按平台分组': '# Group by platform',
        '需要同时采访两个平台的': 'Those needing interview on both platforms',
        '# 未指定平台：两个平台都采访': '# Unspecified platform: interview both',
        '# 把 both_platforms_interviews 拆分到两个平台': '# Split both_platforms_interviews into two platforms',
        '# 处理Twitter平台的采访': '# Process Twitter platform interviews',
        '警告: 无法获取Twitter Agent': 'Warning: Could not get Twitter Agent',
        'Twitter批量Interview失败': 'Twitter batch Interview failed',
        '# 处理Reddit平台的采访': '# Process Reddit platform interviews',
        '警告: 无法获取Reddit Agent': 'Warning: Could not get Reddit Agent',
        'Reddit批量Interview失败': 'Reddit batch Interview failed',
        '批量Interview完成:': 'Batch Interview completed:',
        '没有成功的采访': 'No successful interviews',
        '从数据库获取最新的Interview结果': 'Get latest Interview result from database',
        '# 查询最新的Interview记录': '# Query latest Interview record',
        '读取Interview结果失败': 'Failed to read Interview result',
        '处理所有待处理命令': 'Process all pending commands',
        'True 表示继续运行，False 表示应该退出': 'True to continue running, False to exit',
        '收到IPC命令': 'Received IPC command',
        '收到关闭环境命令': 'Received close environment command',
        '环境即将关闭': 'Environment is about to close',
        '收到退出信号，在第': 'Shutdown signal received, stopping simulation at round',
        '轮停止模拟': '',
        '收到关闭环境命令，退出等待模式': 'Received close environment command, exiting wait mode',
        '未知命令类型': 'Unknown command type',
        '警告: 收到未知命令类型': 'Warning: Received unknown command type',
        '加载配置文件': 'Load configuration file',
        '# 需要过滤掉的非核心动作类型（这些动作对分析价值较低）': '# Non-core action types to filter out (low analysis value)',
        '# 动作类型映射表（数据库中的名称 -> 标准名称）': '# Action type mapping table (name in database -> standard name)',
        '从 simulation_config 中获取 agent_id -> entity_name 的映射': 'Get agent_id -> entity_name mapping from simulation_config',
        '这样可以在 actions.jsonl 中显示真实的实体名称，而不是 \"Agent_0\" 这样的代号': 'This allows displaying real entity names in actions.jsonl instead of code names like \"Agent_0\"',
        'agent_id -> entity_name 的映射字典': 'Mapping dictionary of agent_id -> entity_name',
        '从数据库中获取新的动作记录，并补充完整的上下文信息': 'Fetch new action records from database and supplement with full context information',
        '上次读取的最大 rowid 值（使用 rowid 而不是 created_at，因为不同平台的 created_at 格式不同）': 'Last rowid value read (use rowid instead of created_at because created_at formats differ across platforms)',
        '动作列表，每个元素包含 agent_id, agent_name, action_type, action_args（含上下文信息）': 'List of actions, each containing agent_id, agent_name, action_type, action_args (with context)',
        '新的最大 rowid 值': 'New maximum rowid value',
        '# 使用 rowid 来追踪已处理的记录（rowid 是 SQLite 的内置自增字段）': '# Use rowid to track processed records (rowid is SQLite\'s built-in autoincrement field)',
        '# 这样可以避免 created_at 格式差异问题（Twitter 用整数，Reddit 用日期时间字符串）': '# This avoids issues with created_at format differences (Twitter uses integers, Reddit uses datetime strings)',
        '# 更新最大 rowid': '# Update maximum rowid',
        '# 过滤非核心动作': '# Filter non-core actions',
        '# 解析动作参数': '# Parse action parameters',
        '# 精简 action_args，只保留关键字段（保留完整内容，不截断）': '# Streamline action_args, keeping only key fields (keep full content, no truncation)',
        '# 转换动作类型名称': '# Convert action type name',
        '# 补充上下文信息（帖子内容、用户名等）': '# Supplement context information (post content, username, etc.)',
        '读取数据库动作失败': 'Failed to read database actions',
        '为动作补充上下文信息（帖子内容、用户名等）': 'Supplement actions with context information (post content, username, etc.)',
        '动作参数（会被修改）': 'Action parameters (will be modified)',
        '# 点赞/踩帖子：补充帖子内容和作者': '# Like/Dislike post: supplement post content and author',
        '# 转发帖子：补充原帖内容和作者': '# Repost: supplement original post content and author',
        '# 转发帖子的 original_post_id 指向原帖': '# Repost original_post_id points to the original post',
        '# 引用帖子：补充原帖内容、作者和引用评论': '# Quote post: supplement original post content, author, and quote comment',
        '# 获取引用帖子的评论内容（quote_content）': '# Get comment content of the quoted post (quote_content)',
        '# 关注用户：补充被关注用户的名称': '# Follow user: supplement followed user\'s name',
        '# 从 follow 表获取 followee_id': '# Get followee_id from follow table',
        '# 屏蔽用户：补充被屏蔽用户的名称': '# Mute user: supplement muted user\'s name',
        '# 从 action_args 中获取 user_id 或 target_id': '# Get user_id or target_id from action_args',
        '# 点赞/踩评论：补充评论内容和作者': '# Like/Dislike comment: supplement comment content and author',
        '# 发表评论：补充所评论的帖子信息': '# Create comment: supplement information of the post being commented on',
        '# 补充上下文失败不影响主流程': '# Failure to supplement context does not affect main process',
        '补充动作上下文失败': 'Failed to supplement action context',
        '获取帖子信息': 'Get post information',
        '包含 content 和 author_name 的字典，或 None': 'Dictionary containing content and author_name, or None',
        '# 优先使用 agent_names 中的名称': '# Prioritize names from agent_names',
        '# 从 user 表获取名称': '# Get name from user table',
        '获取用户名称': 'Get username',
        '获取评论信息': 'Get comment information',
        '创建LLM模型': 'Create LLM model',
        '支持加速 LLM 配置（如果可用）': 'speed up LLM configuration (if available)',
        '加速配置（可选）': 'Boost LLM (optional)',
        '根据时间和配置决定本轮激活哪些Agent': 'Determine which agents to activate this round based on time and configuration',
        '平台模拟结果容器': 'Platform simulation result container',
        '运行Twitter模拟': 'Run Twitter simulation',
        '最大模拟轮数（可选，用于截断过长的模拟）': 'Maximum simulation rounds (optional, used to truncate long simulations)',
        '包含env和agent_graph的结果对象': 'Result object containing env and agent_graph',
        '环境已启动': 'Environment started',
        '# 跟踪数据库中最后处理的行号（使用 rowid 避免 created_at 格式差异）': '# Track last rowid processed in database (rowid avoids created_at format issues)',
        '# 记录 round 0 开始（初始事件阶段）': '# Record round 0 start (bootstrap/initial events phase)',
        '已执行': 'Executed',
        '条 round 0 bootstrap 动作': 'round 0 bootstrap actions',
        '# 记录 round 0 结束': '# Record round 0 end',
        '# 主模拟循环': '# Main simulation loop',
        '# 如果指定了最大轮数，则截断': '# Truncate rounds if max_rounds is specified',
        '轮数已截断': 'Rounds truncated',
        '# 检查是否收到退出信号': '# Check for shutdown signal',
        '# 无论是否有活跃agent，都记录round开始': '# Record round start regardless of active agents',
        '# 没有活跃agent时也记录round结束（actions_count=0）': '# Record round end even if no active agents (actions_count=0)',
        '# 无论是否有活跃agent，都记录round结束（actions_count=0）': '# Record round end even if no active agents (actions_count=0)',
        '# 从数据库获取实际执行的动作并记录': '# Fetch actions actually performed from database and record',
        '# 注意：不关闭环境，保留给Interview使用': '# Note: Do not close environment, keep it for Interview',
        '模拟循环完成! 耗时:': 'Simulation loop completed! Elapsed:',
        '秒, 总动作:': 's, Total actions:',
        '运行Reddit模拟': 'Run Reddit simulation',
        '# 同理，不关闭环境，保留给Interview使用': '# Similarly, do not close environment, keep it for Interview',
        '开始双平台模拟': 'Starting dual-platform simulation',
        '主模拟初始化...': 'Main simulation initialization...',
        '开始 Twitter 模拟': 'Starting Twitter simulation',
        'Twitter模拟异常': 'Twitter simulation exception',
        '开始 Reddit 模拟': 'Starting Reddit simulation',
        'Reddit模拟异常': 'Reddit simulation exception',
        '双平台模拟并行运行中...': 'Dual-platform simulation running in parallel...',
        '等待 60 秒以确保环境完全启动...': 'Waiting 60 seconds to ensure environment is fully started...',
        '环境已准备就绪，当前状态:': 'Environment ready, current status:',
        '双平台并发模拟中': 'Dual-platform concurrent simulation',
        '# 注意：主进程不应该被阻塞，Twitter/Reddit 模拟都在后台协程中': '# Note: Main process should not be blocked, simulations run in background coroutines',
        '# 但是我们需要主循环来定期刷新 actions.jsonl': '# But we need a main loop to periodically refresh actions.jsonl',
        '# 主循环：定期刷新 actions.jsonl': '# Main loop: Periodically refresh actions.jsonl',
        '# 读取 Twitter 动作记录': '# Reading Twitter action records',
        '# 记录 Twitter 动作': '# Log Twitter actions',
        '# 读取 Reddit 动作记录': '# Reading Reddit action records',
        '# 记录 Reddit 动作': '# Log Reddit actions',
        '# 如果两个协程都结束了，则退出轮询': '# Exit polling if both coroutines finished',
        '所有模拟任务已完成': 'All simulation tasks completed',
        '# 完成后进入等待命令模式': '# Enter command-wait mode after completion',
        '模拟已完成，环境保持开启并由 IPC 控制': 'Simulation completed, environment kept open and controlled via IPC',
        '手动中断模拟': 'Simulation interrupted manually',
        '主模拟程序退出': 'Main simulation program exit',
        '加载配置...': 'Loading configuration...',
        '# 主函数': '# Main function',
        '设置': 'Setting',
        '平台': 'platform',
        '双平台': 'dual platforms',
        '环境状态刷新': 'Environment status refreshed',
    }

    # Order by key length descending to avoid partial replacements
    sorted_keys = sorted(translations.keys(), key=len, reverse=True)

    for key in sorted_keys:
        content = content.replace(key, translations[key])
    
    # Clean up any leftover Chinese punctuation if necessary
    content = content.replace('，', ',').replace('。', '.').replace('：', ':').replace('！', '!').replace('？', '?')
    content = content.replace('（', '(').replace('）', ')')

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

def process_all_files():
    scripts_dir = r'c:\Users\serge\OneDrive\Documents\GitHub\ASKTHEPEOPLE\backend\scripts'
    files = [
        os.path.join(scripts_dir, 'run_parallel_simulation.py'),
        os.path.join(scripts_dir, 'run_twitter_simulation.py'),
        os.path.join(scripts_dir, 'run_reddit_simulation.py'),
        os.path.join(scripts_dir, 'test_profile_format.py'),
        os.path.join(scripts_dir, 'action_logger.py'),
    ]
    for file_path in files:
        if os.path.exists(file_path):
            print(f"Translating {file_path}...")
            translate_file(file_path)

if __name__ == "__main__":
    process_all_files()
