"""Prepare local runtime secrets for development and the transition deployment.

Writes two files in the repository root:
- ``.env`` (merged): adds the LLM provider keys if absent. Existing keys win.
- ``.env.transition`` (mode 0600): the single-host transition compose topology's
  full runtime secret set, per ``docs/release/RUNBOOK.md``.

The NVIDIA (NIM) API key is read with ``getpass`` so it is never echoed and
never printed. It is only written to the two local files above; both are
gitignored.

Usage:
    python backend/scripts/prepare_local_secrets.py
    python backend/scripts/prepare_local_secrets.py --from C:\\path\\to\\.env
        (reuse an existing .env's LLM_API_KEY instead of prompting, so the key
        is typed exactly once across a development checkout and a deploy clone)

Exit codes: 0 prepared, 78 invalid input or unusable target.
"""

from __future__ import annotations

import argparse
import getpass
import os
import secrets
import stat
import subprocess
import sys
from pathlib import Path

# NVIDIA's OpenAI-compatible catalog endpoint. The backend's LLMClient passes
# this straight into the OpenAI SDK as base_url.
DEFAULT_LLM_BASE_URL = "https://integrate.api.nvidia.com/v1"
DEFAULT_LLM_MODEL_NAME = "meta/llama-3.3-70b-instruct"

REPO_ROOT = Path(__file__).resolve().parents[2]

_ENV_KEYS_NEEDED = ("LLM_API_KEY", "LLM_BASE_URL", "LLM_MODEL_NAME")

_TRANSITION_TEMPLATE = """\
# Single-host transition topology runtime secrets (docs/release/RUNBOOK.md).
# Generated by backend/scripts/prepare_local_secrets.py — mode 0600 required.
# NEVER commit this file. NEVER place the access key in a URL.
FLASK_DEBUG=false
SECRET_KEY={secret_key}
APP_TOKEN={app_token}
REQUIRE_APP_AUTH=true
LLM_API_KEY={llm_api_key}
LLM_BASE_URL={llm_base_url}
LLM_MODEL_NAME={llm_model_name}
ZEP_API_KEY={zep_api_key}
CORS_ORIGINS=http://localhost:5001,http://127.0.0.1:5001
DATABASE_URL=sqlite:////app/backend/instance/askthepeople.db
BUILD_REVISION={build_revision}
"""


def _fail(code: str) -> int:
    print(code, file=sys.stderr)
    return 78


def _read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, _, value = line.partition("=")
        values[name.strip()] = value.strip()
    return values


def _merge_env(path: Path, additions: dict[str, str]) -> None:
    existing: dict[str, str] = {}
    lines: list[str] = []
    if path.exists():
        for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            lines.append(raw_line)
            line = raw_line.strip()
            if line and not line.startswith("#") and "=" in line:
                name, _, _ = line.partition("=")
                existing[name.strip()] = line
    appended = False
    for name, value in additions.items():
        if name in existing:
            continue
        lines.append(f"{name}={value}")
        appended = True
    if not appended and path.exists():
        return
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _git_revision() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return ""


def _prompt_for_key() -> str:
    print("Enter the NVIDIA (NIM) API key (input hidden):", flush=True)
    key = getpass.getpass("")
    if not key or not key.strip():
        return _fail("llm_api_key_required")
    return key.strip()


def _reuse_key_from(path: Path) -> str | None:
    values = _read_env_file(path)
    return values.get("LLM_API_KEY")


def prepare(target: Path, reuse_from: Path | None) -> int:
    if not target.is_dir():
        return _fail("target_invalid")

    if reuse_from is not None:
        llm_api_key = _reuse_key_from(reuse_from)
        if not llm_api_key:
            return _fail("llm_api_key_required")
        print("Reused LLM_API_KEY from the existing .env (not printed).")
    else:
        llm_api_key = _prompt_for_key()
        if llm_api_key == 78:
            return 78

    llm_base_url = os.environ.get("LLM_BASE_URL") or DEFAULT_LLM_BASE_URL
    llm_model_name = os.environ.get("LLM_MODEL_NAME") or DEFAULT_LLM_MODEL_NAME
    zep_api_key = secrets.token_urlsafe(32)
    secret_key = secrets.token_urlsafe(32)
    app_token = secrets.token_urlsafe(32)
    build_revision = _git_revision()

    # Development checkout: merge the LLM keys into .env. Existing keys win.
    _merge_env(
        target / ".env",
        {
            "LLM_API_KEY": llm_api_key,
            "LLM_BASE_URL": llm_base_url,
            "LLM_MODEL_NAME": llm_model_name,
        },
    )

    # Transition deployment: write the full runtime secret set, mode 0600.
    transition_path = target / ".env.transition"
    transition_path.write_text(
        _TRANSITION_TEMPLATE.format(
            secret_key=secret_key,
            app_token=app_token,
            llm_api_key=llm_api_key,
            llm_base_url=llm_base_url,
            llm_model_name=llm_model_name,
            zep_api_key=zep_api_key,
            build_revision=build_revision,
        ),
        encoding="utf-8",
    )
    os.chmod(
        transition_path,
        stat.S_IRUSR | stat.S_IWUSR,  # 0600 per the runbook
    )

    print(f"Prepared {target / '.env'} (LLM keys merged).")
    print(f"Prepared {transition_path} (mode 0600).")
    if not build_revision:
        print(
            "Warning: BUILD_REVISION could not be resolved from git; "
            "set it manually before docker compose up.",
            file=sys.stderr,
        )
    print("ZEP_API_KEY was generated locally; Zep graph features remain "
          "experimental and non-functional without a real Zep account.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--from",
        dest="reuse_from",
        type=Path,
        default=None,
        help="Reuse LLM_API_KEY from an existing .env instead of prompting.",
    )
    parser.add_argument(
        "--target",
        dest="target",
        type=Path,
        default=REPO_ROOT,
        help="Repository root to prepare (default: the repo containing this script).",
    )
    args = parser.parse_args()
    return prepare(args.target.resolve(), args.reuse_from.resolve() if args.reuse_from else None)


if __name__ == "__main__":
    raise SystemExit(main())
