import os

filepath = r"c:\Users\serge\OneDrive\Documents\GitHub\ASKTHEPEOPLE\backend\app\services\simulation_manager.py"
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "OASIS模拟管理器": "OASIS Simulation Manager",
    "管理Twitter和Reddit双平台并行模拟": "Manages parallel Twitter and Reddit simulations",
    "使用预设脚本 + LLM智能生成配置参数": "Uses preset scripts + LLM to intelligently generate configuration parameters",
    "模拟状态": "Simulation Status",
    "平台类型": "Platform Type",
    "平台启用状态": "Platform enable status",
    "状态": "Status",
    "准备阶段数据": "Preparation stage data",
    "配置生成信息": "Configuration generation info",
    "运行时数据": "Runtime data",
    "时间戳": "Timestamps",
    "错误信息": "Error information",
    "完整状态字典（内部使用）": "Complete state dictionary (internal use)",
    "简化状态字典（API返回使用）": "Simplified state dictionary (API response use)",
    "模拟管理器": "Simulation Manager",
    "核心功能：": "Core features:",
    "1. 从Zep图谱读取实体并过滤": "1. Read and filter entities from Zep graph",
    "2. 生成OASIS Agent Profile": "2. Generate OASIS Agent Profile",
    "3. 使用LLM智能生成模拟配置参数": "3. Intelligent generation of simulation config via LLM",
    "4. 准备预设脚本所需的所有文件": "4. Prepare all files needed for preset scripts",
    "模拟数据存储目录": "Simulation data storage directory",
    "确保目录存在": "Ensure directory exists",
    "内存中的模拟状态缓存": "In-memory simulation state cache",
    "获取模拟数据目录": "Get simulation data directory",
    "保存模拟状态到文件": "Save simulation state to file",
    "从文件加载模拟状态": "Load simulation state from file",
    "创建新的模拟": "Create new simulation",
    "项目ID": "Project ID",
    "Zep图谱ID": "Zep Graph ID",
    "是否启用Twitter模拟": "Whether to enable Twitter simulation",
    "是否启用Reddit模拟": "Whether to enable Reddit simulation",
    "创建模拟: ": "Created simulation: ",
    "准备模拟环境（全程自动化）": "Prepare simulation environment (fully automated)",
    "步骤：": "Steps:",
    "2. 为每个实体生成OASIS Agent Profile（可选LLM增强，支持并行）": "2. Generate OASIS Agent Profile for each entity (optional LLM enhancement, supports parallel)",
    "3. 使用LLM智能生成模拟配置参数（时间、活跃度、发言频率等）": "3. Generate simulation config params via LLM (time, activity, post frequency, etc.)",
    "4. 保存配置文件和Profile文件": "4. Save config files and Profile files",
    "5. 复制预设脚本到模拟目录": "5. Copy preset scripts to simulation directory",
    "模拟ID": "Simulation ID",
    "模拟需求描述（用于LLM生成配置）": "Simulation requirement description (for LLM)",
    "原始文档内容（用于LLM理解背景）": "Original document content (for LLM context)",
    "预定义的实体类型（可选）": "Predefined entity types (optional)",
    "是否使用LLM生成详细人设": "Whether to use LLM for detailed persona",
    "进度回调函数 (stage, progress, message)": "Progress callback function (stage, progress, message)",
    "并行生成人设的数量，默认3": "Number of parallel persona generations, default 3",
    "模拟不存在: ": "Simulation does not exist: ",
    "========== 阶段1: 读取并过滤实体 ==========": "========== Phase 1: Read and filter entities ==========",
    "正在连接Zep图谱...": "Connecting to Zep graph...",
    "正在读取节点数据...": "Reading node data...",
    "完成，共 ": "Completed, total ",
    " 个实体": " entities",
    "没有找到符合条件的实体，请检查图谱是否正确构建": "No matching entities found, please check if graph was built correctly",
    "========== 阶段2: 生成Agent Profile ==========": "========== Phase 2: Generate Agent Profile ==========",
    "开始生成...": "Starting generation...",
    "传入graph_id以启用Zep检索功能，获取更丰富的上下文": "Pass graph_id to enable Zep retrieval for richer context",
    "设置实时保存的文件路径（优先使用 Reddit JSON 格式）": "Set real-time save paths (prefer Reddit JSON format)",
    "传入graph_id用于Zep检索": "Pass graph_id for Zep retrieval",
    "并行生成数量": "Parallel generation count",
    "实时保存路径": "Real-time save path",
    "输出格式": "Output format",
    "保存Profile文件...": "Saving Profile files...",
    " 个Profile": " Profiles",
    "========== 阶段3: LLM智能生成模拟配置 ==========": "========== Phase 3: LLM intelligent config generation ==========",
    "正在分析模拟需求...": "Analyzing simulation requirements...",
    "正在调用LLM生成配置...": "Calling LLM to generate config...",
    "正在保存配置文件...": "Saving configuration file...",
    "保存配置文件": "Save configuration file",
    "配置生成完成": "Configuration generation completed",
    "注意：运行脚本保留在 backend/scripts/ 目录，不再复制到模拟目录": "Note: scripts are kept in backend/scripts/ and not copied to simulation dir",
    "启动模拟时，simulation_runner 会从 scripts/ 目录运行脚本": "simulation_runner runs from scripts/ directory on start",
    "更新状态": "Update status",
    "模拟准备完成: ": "Simulation preparation completed: ",
    "模拟准备失败: ": "Simulation preparation failed: ",
    "获取模拟状态": "Get simulation status",
    "列出所有模拟": "List all simulations",
    "跳过隐藏文件（如 .DS_Store）和非目录文件": "Skip hidden files (e.g. .DS_Store) and non-directory files",
    "获取模拟的Agent Profile": "Get simulation Agent Profile",
    "获取模拟配置": "Get simulation configuration",
    "获取运行说明": "Get running instructions",
    "运行模拟 (脚本位于 ": "Run simulation (script located at ",
    "单独运行Twitter: ": "Run Twitter separately: ",
    "单独运行Reddit: ": "Run Reddit separately: ",
    "并行运行双平台: ": "Run both platforms in parallel: ",
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(text)

print("done")
