import os

filepath = r"c:\Users\serge\OneDrive\Documents\GitHub\ASKTHEPEOPLE\backend\app\services\zep_graph_memory_updater.py"
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "Zep图谱记忆更新服务": "Zep Graph Memory Update Service",
    "将模拟中的Agent活动动态更新到Zep图谱中": "Dynamically updates Agent activities from the simulation into the Zep graph",
    "Agent活动记录": "Agent activity record",
    "将活动转换为可以发送给Zep的文本描述": "Convert activity to a text description that can be sent to Zep",
    "采用自然语言描述格式，让Zep能够从中提取实体和关系": "Uses a natural language description format so Zep can extract entities and relationships",
    "不添加模拟相关的前缀，避免误导图谱更新": "Does not add simulation-related prefixes to avoid misleading graph updates",
    "根据不同的动作类型生成不同的描述": "Generate different descriptions based on different action types",
    "直接返回 \"agent名称: 活动描述\" 格式，不添加模拟前缀": "Directly return 'agent name: activity description' format, do not add simulation prefix",
    "发布了一条帖子：「{content}」": "published a post: '{content}'",
    "发布了一条帖子": "published a post",
    "点赞帖子 - 包含帖子原文和作者信息": "Like post - contains original post and author info",
    "点赞了{post_author}的帖子：「{post_content}」": "liked {post_author}'s post: '{post_content}'",
    "点赞了一条帖子：「{post_content}」": "liked a post: '{post_content}'",
    "点赞了{post_author}的一条帖子": "liked a post by {post_author}",
    "点赞了一条帖子": "liked a post",
    "踩帖子 - 包含帖子原文和作者信息": "Dislike post - contains original post and author info",
    "踩了{post_author}的帖子：「{post_content}」": "disliked {post_author}'s post: '{post_content}'",
    "踩了一条帖子：「{post_content}」": "disliked a post: '{post_content}'",
    "踩了{post_author}的一条帖子": "disliked a post by {post_author}",
    "踩了一条帖子": "disliked a post",
    "转发帖子 - 包含原帖内容和作者信息": "Repost - contains original post and author info",
    "转发了{original_author}的帖子：「{original_content}」": "reposted {original_author}'s post: '{original_content}'",
    "转发了一条帖子：「{original_content}」": "reposted a post: '{original_content}'",
    "转发了{original_author}的一条帖子": "reposted a post by {original_author}",
    "转发了一条帖子": "reposted a post",
    "引用帖子 - 包含原帖内容、作者信息和引用评论": "Quote post - contains original post, author info, and quote comment",
    "引用了{original_author}的帖子「{original_content}」": "quoted {original_author}'s post '{original_content}'",
    "引用了一条帖子「{original_content}」": "quoted a post '{original_content}'",
    "引用了{original_author}的一条帖子": "quoted a post by {original_author}",
    "引用了一条帖子": "quoted a post",
    "，并评论道：「{quote_content}」": ", and commented: '{quote_content}'",
    "关注用户 - 包含被关注用户的名称": "Follow user - contains followed user's name",
    "关注了用户「{target_user_name}」": "followed user '{target_user_name}'",
    "关注了一个用户": "followed a user",
    "发表评论 - 包含评论内容和所评论的帖子信息": "Create comment - contains comment content and commented post info",
    "在{post_author}的帖子「{post_content}」下评论道：「{content}」": "commented under {post_author}'s post '{post_content}': '{content}'",
    "在帖子「{post_content}」下评论道：「{content}」": "commented under post '{post_content}': '{content}'",
    "在{post_author}的帖子下评论道：「{content}」": "commented under {post_author}'s post: '{content}'",
    "评论道：「{content}」": "commented: '{content}'",
    "发表了评论": "created a comment",
    "点赞评论 - 包含评论内容和作者信息": "Like comment - contains comment content and author info",
    "点赞了{comment_author}的评论：「{comment_content}」": "liked {comment_author}'s comment: '{comment_content}'",
    "点赞了一条评论：「{comment_content}」": "liked a comment: '{comment_content}'",
    "点赞了{comment_author}的一条评论": "liked a comment by {comment_author}",
    "点赞了一条评论": "liked a comment",
    "踩评论 - 包含评论内容和作者信息": "Dislike comment - contains comment content and author info",
    "踩了{comment_author}的评论：「{comment_content}」": "disliked {comment_author}'s comment: '{comment_content}'",
    "踩了一条评论：「{comment_content}」": "disliked a comment: '{comment_content}'",
    "踩了{comment_author}的一条评论": "disliked a comment by {comment_author}",
    "踩了一条评论": "disliked a comment",
    "搜索帖子 - 包含搜索关键词": "Search posts - contains search keyword",
    "搜索了「{query}」": "searched for '{query}'",
    "进行了搜索": "performed a search",
    "搜索用户 - 包含搜索关键词": "Search user - contains search keyword",
    "搜索了用户「{query}」": "searched for user '{query}'",
    "搜索了用户": "searched for a user",
    "屏蔽用户 - 包含被屏蔽用户的名称": "Mute user - contains muted user's name",
    "屏蔽了用户「{target_user_name}」": "muted user '{target_user_name}'",
    "屏蔽了一个用户": "muted a user",
    "对于未知的动作类型，生成通用描述": "Generate generic description for unknown action types",
    "执行了{self.action_type}操作": "executed {self.action_type} operation",
    "Zep图谱记忆更新器": "Zep Graph Memory Updater",
    "监控模拟的actions日志文件，将新的agent活动实时更新到Zep图谱中。": "Monitors simulation actions log file, updates new agent activities to Zep graph in real-time.",
    "按平台分组，每累积BATCH_SIZE条活动后批量发送到Zep。": "Groups by platform, accumulates BATCH_SIZE activities before batch sending to Zep.",
    "所有有意义的行为都会被更新到Zep，action_args中会包含完整的上下文信息：": "All meaningful behaviors are updated to Zep, action_args contains full context information:",
    "- 点赞/踩的帖子原文": "- Liked/disliked original post",
    "- 转发/引用的帖子原文": "- Reposted/quoted original post",
    "- 关注/屏蔽的用户名": "- Followed/muted username",
    "- 点赞/踩的评论原文": "- Liked/disliked original comment",
    "批量发送大小（每个平台累积多少条后发送）": "Batch send size (accumulation threshold per platform)",
    "平台名称映射（用于控制台显示）": "Platform name mapping (for console display)",
    "'世界1'": "'World 1'",
    "'世界2'": "'World 2'",
    "发送间隔（秒），避免请求过快": "Send interval (seconds) to prevent rate limiting",
    "重试配置": "Retry configuration",
    "秒": "seconds",
    "初始化更新器": "Initialize updater",
    "Zep API Key（可选，默认从配置读取）": "Zep API Key (optional, defauts to config)",
    "ZEP_API_KEY未配置": "ZEP_API_KEY not configured",
    "活动队列": "Activity queue",
    "按平台分组的活动缓冲区（每个平台各自累积到BATCH_SIZE后批量发送）": "Platform-grouped activity buffer (accumulates up to BATCH_SIZE per platform)",
    "控制标志": "Control flags",
    "统计": "Statistics",
    "实际添加到队列的活动数": "Total activities added to queue",
    "成功发送到Zep的批次数": "Batches successfully sent to Zep",
    "成功发送到Zep的活动条数": "Activities successfully sent to Zep",
    "发送失败的批次数": "Failed batches",
    "被过滤跳过的活动数（DO_NOTHING）": "Activities skipped (DO_NOTHING)",
    " 初始化完成: graph_id": " initialized: graph_id",
    "获取平台的显示名称": "Get platform display name",
    "启动后台工作线程": "Start background worker thread",
    " 已启动: graph_id": " started: graph_id",
    "停止后台工作线程": "Stop background worker thread",
    "发送剩余的活动": "Send remaining activities",
    " 已停止: graph_id": " stopped: graph_id",
    "添加一个agent活动到队列": "Add an agent activity to the queue",
    "所有有意义的行为都会被添加到队列，包括：": "All meaningful behaviors added to the queue, including:",
    "CREATE_POST（发帖）": "CREATE_POST",
    "CREATE_COMMENT（评论）": "CREATE_COMMENT",
    "QUOTE_POST（引用帖子）": "QUOTE_POST",
    "SEARCH_POSTS（搜索帖子）": "SEARCH_POSTS",
    "SEARCH_USER（搜索用户）": "SEARCH_USER",
    "LIKE_POST/DISLIKE_POST（点赞/踩帖子）": "LIKE_POST/DISLIKE_POST",
    "REPOST（转发）": "REPOST",
    "FOLLOW（关注）": "FOLLOW",
    "MUTE（屏蔽）": "MUTE",
    "LIKE_COMMENT/DISLIKE_COMMENT（点赞/踩评论）": "LIKE_COMMENT/DISLIKE_COMMENT",
    "action_args中会包含完整的上下文信息（如帖子原文、用户名等）。": "action_args will contain full context info (e.g., original post, username).",
    "跳过DO_NOTHING类型的活动": "Skip DO_NOTHING type activities",
    "添加活动到Zep队列: ": "Added activity to Zep queue: ",
    "从字典数据添加活动": "Add activity from dictionary data",
    "从actions.jsonl解析的字典数据": "Parsed dict data from actions.jsonl",
    "平台名称 (twitter/reddit)": "Platform name (twitter/reddit)",
    "跳过事件类型的条目": "Skip event type entries",
    "后台工作循环 - 按平台批量发送活动到Zep": "Background worker loop - batch send activities to Zep by platform",
    "尝试从队列获取活动（超时1秒）": "Try to get activity from queue (1s timeout)",
    "将活动添加到对应平台的缓冲区": "Add activity to corresponding platform buffer",
    "检查该平台是否达到批量大小": "Check if platform reached batch size",
    "释放锁后再发送": "Release lock before sending",
    "发送间隔，避免请求过快": "Send interval to avoid rate limiting",
    "工作循环异常: ": "Worker loop exception: ",
    "批量发送活动到Zep图谱（合并为一条文本）": "Batch send activities to Zep graph (merged as single text)",
    "Agent活动列表": "Agent activity list",
    "平台名称": "Platform name",
    "将多条活动合并为一条文本，用换行分隔": "Merge multiple activities into one text, separated by newline",
    "带重试的发送": "Send with retries",
    "成功批量发送 ": "Successfully batch sent ",
    " 条": " ",
    "活动到图谱 ": "activities to graph ",
    "批量内容预览: ": "Batch content preview: ",
    "批量发送到Zep失败 (尝试 ": "Batch send to Zep failed (attempt ",
    "批量发送到Zep失败，已重试": "Batch send to Zep failed, retried",
    "次: ": "times: ",
    "发送队列和缓冲区中剩余的活动": "Send remaining activities in queue and buffers",
    "首先处理队列中剩余的活动，添加到缓冲区": "Process remaining activities in queue, add to buffer first",
    "然后发送各平台缓冲区中剩余的活动（即使不足BATCH_SIZE条）": "Then send remaining activities in platform buffers (even if under BATCH_SIZE)",
    "发送": "Sending ",
    "平台剩余的 ": "platform's remaining ",
    "条活动": "activities",
    "清空所有缓冲区": "Clear all buffers",
    "获取统计信息": "Get statistics",
    "添加到队列的活动总数": "Total activities added to queue",
    "成功发送的批次数": "Batches successfully sent",
    "成功发送的活动条数": "Items successfully sent",
    "发送失败的批次数": "Failed batches count",
    "被过滤跳过的活动数（DO_NOTHING）": "Skipped activities count (DO_NOTHING)",
    "各平台缓冲区大小": "Buffer sizes by platform",
    "管理多个模拟的Zep图谱记忆更新器": "Manages Zep graph memory updaters for multiple simulations",
    "每个模拟可以有自己的更新器实例": "Each simulation can have its own updater instance",
    "为模拟创建图谱记忆更新器": "Create graph memory updater for simulation",
    "模拟ID": "Simulation ID",
    "Zep图谱ID": "Zep Graph ID",
    "ZepGraphMemoryUpdater实例": "ZepGraphMemoryUpdater instance",
    "如果已存在，先停止旧的": "If exists, stop the old one first",
    "创建图谱记忆更新器: simulation_id=": "Created graph memory updater: simulation_id=",
    "获取模拟的更新器": "Get updater for simulation",
    "停止并移除模拟的更新器": "Stop and remove updater for simulation",
    "已停止图谱记忆更新器: simulation_id=": "Stopped graph memory updater: simulation_id=",
    "防止 stop_all 重复调用的标志": "Flag to prevent repeated stop_all calls",
    "停止所有更新器": "Stop all updaters",
    "防止重复调用": "Prevent repeated calls",
    "停止更新器失败: simulation_id=": "Failed to stop updater: simulation_id=",
    "已停止所有图谱记忆更新器": "Stopped all graph memory updaters",
    "获取所有更新器的统计信息": "Get statistics for all updaters",
    "ZepGraphMemoryUpdater 初始化完成": "ZepGraphMemoryUpdater initialized",
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(text)

print("done")
