import os

filepath = r"c:\Users\serge\OneDrive\Documents\GitHub\ASKTHEPEOPLE\backend\app\services\zep_tools.py"
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "【Deep Analysis of Future Predictions】": "## Deep Analysis of Future Predictions",
    "分析问题: {self.query}": f"Analysis Question: {{self.query}}",
    "预测场景: {self.simulation_requirement}": f"Prediction Scenario: {{self.simulation_requirement}}",
    "### 预测数据统计": "### Prediction Data Statistics",
    "- 相关预测事实: {self.total_facts}": f"- Relevant Predicted Facts: {{self.total_facts}}",
    "- 涉及实体: {self.total_entities}": f"- Entities Involved: {{self.total_entities}}",
    "- 关系链条: {self.total_relationships}": f"- Relationship Chains: {{self.total_relationships}}",
    "### 分析子问题": "### Analyzed Sub-queries",
    "### 【核心事实】 (请在报告中引用这些原始文本)": "### 【Key Facts】(Please cite these original texts in the report)",
    "### 【核心实体】": "### 【Core Entities】",
    "### 关系链条": "### Relationship Chains",
    "## 广度搜索结果 (未来全景图)": "## Wide Search Results (Future Panorama)",
    "查询: {self.query}": f"Query: {{self.query}}",
    "### 统计信息": "### Statistical information",
    "- 节点总数: {self.total_nodes}": f"- Total Nodes: {{self.total_nodes}}",
    "- 关系总数: {self.total_edges}": f"- Total Edges: {{self.total_edges}}",
    "- 当前活动事实: {self.active_count}": f"- Currently Active Facts: {{self.active_count}}",
    "- 历史/过期事实: {self.historical_count}": f"- Historical/Expired Facts: {{self.historical_count}}",
    "### 【当前活动事实】 (模拟结果原始记录)": "### 【Currently Active Facts】 (Simulation Result Originals)",
    "### 【历史/过期事实】 (演化记录)": "### 【Historical/Expired Facts】 (Evolutionary Record)",
    "### 【涉及实体】": "### 【Involved Entities】",
    "## 深度访谈报告": "## Deep Interview Report",
    "**访谈主题:** {self.interview_topic}": f"**Interview Topic:** {{self.interview_topic}}",
    "**受访人数:** {self.interviewed_count} / {self.total_agents} 名模拟 Agent": f"**Number of Interviewees:** {{self.interviewed_count}} / {{self.total_agents}} simulated Agents",
    "### 选取逻辑": "### Selection Reasoning",
    "### 访谈实录": "### Interview Transcripts",
    "#### 访谈 #{i}: {interview.agent_name}": f"#### Interview #{{i}}: {{interview.agent_name}}",
    "### 访谈总结与核心观点": "### Interview Summary and Core Perspectives",
    "ZEP_API_KEY 未配置": "ZEP_API_KEY not configured",
    "ZepToolsService 初始化完成": "ZepToolsService initialization complete",
    "延迟初始化LLM客户端": "Delayed initialization of LLM client",
    "带重试机制的API调用": "API call with retry mechanism",
    "第 {attempt + 1} 次尝试失败": f"attempt {{attempt + 1}} failed",
    "秒后重试...": "seconds later retrying...",
    "次尝试后仍失败": "attempts and still failed",
    "图谱语义搜索": "Graph semantic search",
    "使用混合搜索（语义+BM25）在图谱中搜索相关信息。": "Search for relevant info in the graph using hybrid search (semantic + BM25).",
    "如果Zep Cloud的search API不可用，则降级为本地关键词匹配。": "If Zep Cloud search API is unavailable, fallback to local keyword matching.",
    "搜索范围，\"edges\" 或 \"nodes\"": "Search scope, 'edges' or 'nodes'",
    "图谱搜索: graph_id={graph_id}, query={query[:50]}...": f"Graph search: graph_id={{graph_id}}, query={{query[:50]}}...",
    "解析边搜索结果": "Parse edge search results",
    "解析节点搜索结果": "Parse node search results",
    "节点摘要也算作事实": "Node summary also counts as a fact",
    "Zep Search API 失败，尝试本地搜索": "Zep Search API failed, trying local search",
    "本地关键词匹配搜索（作为Zep Search API的降级方案）": "Local keyword matching search (as fallback for Zep Search API)",
    "获取所有边/节点，然后在本地进行关键词匹配": "Get all edges/nodes, then match keywords locally",
    "使用本地搜索: query={query[:30]}...": f"Using local search: query={{query[:30]}}...",
    "提取查询关键词（简单分词）": "Extracting search keywords (simple tokenization)",
    "计算文本与查询的匹配分数": "Calculate match score between text and query",
    "完全匹配查询": "Exact query match",
    "关键词匹配": "Keyword match",
    "获取所有边并匹配": "Get all edges and match",
    "获取节点详情": "Get node detail",
    "获取节点相关的所有边": "Get all edges related to the node",
    "通过获取图谱所有边，然后过滤出与指定节点相关的边": "Retrieve all edges of the graph, then filter those related to the specified node",
    "检查边是否与指定节点相关（作为源或目标）": "Check if edge is related to the specified node (as source or target)",
    "获取 entity_summary 失败": "Failed to get entity_summary",
    "InsightForge 深度洞察检索开始": "InsightForge deep insight retrieval started",
    "正在通过 LLM 生成 3 个分析子问题...": "Generating 3 analysis sub-queries via LLM...",
    "【InsightForge】第 {i+1} 个子问题搜索: {sub_query}": f"【InsightForge】Searching sub-query {{i+1}}: {{sub_query}}",
    "InsightForge 检索完成": "InsightForge retrieval complete",
    "Panorama 广度全景搜索开始": "Panorama wide panorama search started",
    "正在获取图谱全量数据...": "Retrieving full graph data...",
    "正在分类活跃事实与历史事实...": "Classifying active facts and historical facts...",
    "Panorama 搜索完成": "Panorama search complete",
    "开始深度访谈流程": "Starting deep interview process",
    "正在读取所有 Agent 人设文件...": "Reading all Agent persona files...",
    "未找到任何 Agent 人设文件": "No Agent persona files found",
    "正在通过 LLM 选取最相关的受访者并生成问题...": "Selecting most relevant interviewees and generating questions via LLM...",
    "选取受访者失败，请重试": "Failed to select interviewees, please retry",
    "开始进行并行访谈...": "Starting parallel interviews...",
    "共发送 {len(tasks)} 个访谈请求": f"Sent {{len(tasks)}} interview requests",
    "访谈任务 {task.id} 失败": f"Interview task {{task.id}} failed",
    "正在汇总访谈内容...": "Consolidating interview content...",
    "深度访谈流程完成": "Deep interview process complete",
    "深度访谈失败: {str(e)}": f"Deep interview failed: {{str(e)}}",
    "获取受访者摘要": "Get interviewee summary",
    "【分析子问题生成】": "[Analysis Sub-query Generation]",
    "请根据以下信息生成 3 个分析子问题，用于更全面地检索模拟世界的信息。": "Please generate 3 analysis sub-queries based on the following info for a more comprehensive retrieval of simulation world info.",
    "【选取受访者与生成问题】": "[Select Interviewees and Generate Questions]",
    "你现在拥有“上帝视角”，可以直接接触所有参加模拟的 Agent。": "You now have a 'God's View' and can directly contact all Agents participating in the simulation.",
    "你的任务：": "Your task:",
    "1. 仔细阅读所有这些 Agent 的生平/人设，挑选出与访谈主题最相关的 3-5 位 Agent。": "1. Carefully read the bios/personas of all these Agents and select 3-5 that are most relevant to the interview topic.",
    "2. 针对每一位选中的 Agent，根据其身份、立场和访谈主题，设计一个最能挖掘其深度见解的访谈问题。": "2. For each selected Agent, design an interview question that best explores their deep insights based on their identity, stance, and the interview topic.",
    "【访谈内容汇总分析】": "[Interview Content Summary Analysis]",
    "请根据以下几位 Agent 的访谈记录，以“上帝视角”进行汇总分析。": "Please summarize and analyze the interview records of these Agents from a 'God's View'.",
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(text)

print("done")
