import os

filepath = r"c:\Users\serge\OneDrive\Documents\GitHub\ASKTHEPEOPLE\backend\app\services\graph_builder.py"
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "图谱构建服务": "Graph Building Service",
    "接口2：使用Zep API构建Standalone Graph": "Endpoint 2: Build Standalone Graph using Zep API",
    "图谱信息": "Graph Information",
    "负责调用Zep API构建知识图谱": "Responsible for calling Zep API to build knowledge graph",
    "ZEP_API_KEY 未配置": "ZEP_API_KEY not configured",
    "异步构建图谱": "Asynchronously build graph",
    "Args:\n            text: 输入文本": "Args:\n            text: Input text",
    "ontology: 本体定义（来自接口1的输出）": "ontology: Ontology definition (from Endpoint 1 output)",
    "graph_name: 图谱名称": "graph_name: Graph name",
    "chunk_size: 文本块大小": "chunk_size: Text chunk size",
    "chunk_overlap: 块重叠大小": "chunk_overlap: Chunk overlap size",
    "batch_size: 每批发送的块数量": "batch_size: Number of chunks sent per batch",
    "Returns:\n            任务ID": "Returns:\n            Task ID",
    "创建任务": "Create task",
    "在后台线程中执行构建": "Execute building in background thread",
    "图谱构建工作线程": "Graph building worker thread",
    "message=\"开始构建图谱...\"": "message=\"Starting graph building...\"",
    "1. 创建图谱": "1. Create graph",
    "message=f\"图谱已创建: {graph_id}\"": "message=f\"Graph created: {graph_id}\"",
    "2. 设置本体": "2. Set ontology",
    "message=\"本体已设置\"": "message=\"Ontology set\"",
    "3. 文本分块": "3. Text chunking",
    "message=f\"文本已分割为 {total_chunks} 个块\"": "message=f\"Text split into {total_chunks} chunks\"",
    "4. 分批发送数据": "4. Send data in batches",
    "5. 等待Zep处理完成": "5. Wait for Zep processing to complete",
    "message=\"等待Zep处理数据...\"": "message=\"Waiting for Zep to process data...\"",
    "6. 获取图谱信息": "6. Get graph info",
    "message=\"获取图谱信息...\"": "message=\"Getting graph info...\"",
    "完成": "Complete",
    "创建Zep图谱（公开方法）": "Create Zep graph (public method)",
    "设置图谱本体（公开方法）": "Set graph ontology (public method)",
    "抑制 Pydantic v2 关于 Field(default=None) 的警告": "Suppress Pydantic v2 warnings about Field(default=None)",
    "这是 Zep SDK 要求的用法，警告来自动态类创建，可以安全忽略": "This is usage required by Zep SDK; warnings come from dynamic class creation and can be safely ignored",
    "Zep 保留名称，不能作为属性名": "Zep reserved names, cannot be used as attribute names",
    "将保留名称转换为安全名称": "Convert reserved names to safe names",
    "动态创建实体类型": "Dynamically create entity types",
    "创建属性字典和类型注解（Pydantic v2 需要）": "Create attribute dictionary and type annotations (required by Pydantic v2)",
    "使用安全名称": "Use safe name",
    "Zep API 需要 Field 的 description，这是必需的": "Zep API requires Field description, which is mandatory",
    "类型注解": "Type annotation",
    "动态创建类": "Dynamically create class",
    "动态创建边类型": "Dynamically create edge types",
    "创建属性字典和类型注解": "Create attribute dictionary and type annotations",
    "边属性用str类型": "Edge attributes use str type",
    "构建source_targets": "Build source_targets",
    "调用Zep API设置本体": "Call Zep API to set ontology",
    "分批添加文本到图谱，返回所有 episode 的 uuid 列表": "Add text to graph in batches, return list of all episode uuids",
    "构建episode数据": "Build episode data",
    "发送到Zep": "Send to Zep",
    "收集返回的 episode uuid": "Collect returned episode uuids",
    "避免请求过快": "Avoid sending requests too fast",
    "批次 {batch_num} 发送失败": f"Batch {{batch_num}} failed to send",
    "等待所有 episode 处理完成（通过查询每个 episode 的 processed 状态）": "Wait for all episodes to finish processing (by querying processed status of each episode)",
    "无需等待（没有 episode）": "No need to wait (no episodes)",
    "开始等待 {total_episodes} 个文本块处理...": f"Starting to wait for {{total_episodes}} text chunks to process...",
    "部分文本块超时，已完成 {completed_count}/{total_episodes}": f"Some text chunks timed out, completed {{completed_count}}/{{total_episodes}}",
    "检查每个 episode 的处理状态": "Check processing status of each episode",
    "忽略单个查询错误，继续": "Ignore single query error and continue",
    "Zep处理中... {completed_count}/{total_episodes} 完成, {len(pending_episodes)} 待处理 ({elapsed}秒)": f"Zep processing... {{completed_count}}/{{total_episodes}} completed, {{len(pending_episodes)}} pending ({{elapsed}}s)",
    "处理完成: {completed_count}/{total_episodes}": f"Processing complete: {{completed_count}}/{{total_episodes}}",
    "获取图谱信息": "Get graph information",
    "统计实体类型": "Count entity types",
    "获取完整图谱数据（包含详细信息）": "Get full graph data (including details)",
    "包含nodes和edges的字典，包括时间信息、属性等详细数据": "Dictionary containing nodes and edges, including time info, attributes, and other detailed data",
    "创建节点映射用于获取节点名称": "Create node mapping to get node names",
    "获取创建时间": "Get creation time",
    "获取时间信息": "Get time info",
    "获取 episodes": "Get episodes",
    "获取 fact_type": "Get fact_type",
    "删除图谱": "Delete graph",
    "发送第 {batch_num}/{total_batches} 批数据 ({len(batch_chunks)} 块)...": f"Sending batch {{batch_num}}/{{total_batches}} ({{len(batch_chunks)}} chunks)...",
    "图谱构建失败": "Graph building failed",
    "构建失败": "Build failed",
    "开始构建图谱...": "Starting graph building...",
    "图谱已创建": "Graph created",
    "本体已设置": "Ontology set",
    "文本已分割为": "Text split into",
    "等待Zep处理数据...": "Waiting for Zep to process data...",
    "获取图谱信息...": "Getting graph information...",
    "无需等待（没有 episode）": "No need to wait (no episode)",
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(text)

print("done")
