import os

filepath = r"c:\Users\serge\OneDrive\Documents\GitHub\ASKTHEPEOPLE\backend\app\services\report_agent.py"
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "Report Agent服务": "Report Agent Service",
    "使用LangChain + Zep实现ReACT模式的模拟报告生成": "Using LangChain + Zep to implement ReACT-mode simulated report generation",
    "功能：": "Features:",
    "1. 根据模拟需求和Zep图谱信息生成报告": "1. Generate reports based on simulation requirements and Zep graph info",
    "2. 先规划目录结构，然后分段生成": "2. Plan directory structure first, then generate segment by segment",
    "3. 每段采用ReACT多轮思考与反思模式": "3. Each segment uses ReACT multi-round thinking and reflection",
    "4. 支持与用户对话，在对话中自主调用检索工具": "4. Support chat with users, autonomously calling retrieval tools during chat",
    "Report Agent 详细日志记录器": "Report Agent Detailed Logger",
    "在报告文件夹中生成 agent_log.jsonl 文件，记录每一步详细动作。": "Generate agent_log.jsonl in the report folder to record each detailed action.",
    "每行是一个完整的 JSON 对象，包含时间戳、动作类型、详细内容等。": "Each line is a complete JSON object including timestamp, action type, details, etc.",
    "初始化日志记录器": "Initialize logger",
    "Args:\n            report_id: 报告ID，用于确定日志文件路径": "Args:\n            report_id: Report ID, used to determine log file path",
    "确保日志文件所在目录存在": "Ensure log file directory exists",
    "获取从开始到现在的耗时（秒）": "Get elapsed time from start (seconds)",
    "记录一条日志": "Record a log entry",
    "Args:\n            action: 动作类型，如 'start', 'tool_call', 'llm_response', 'section_complete' 等": "Args:\n            action: Action type, such as 'start', 'tool_call', 'llm_response', 'section_complete', etc.",
    "stage: 当前阶段，如 'planning', 'generating', 'completed'": "stage: Current stage, e.g., 'planning', 'generating', 'completed'",
    "details: 详细内容字典，不截断": "details: Detailed content dictionary, not truncated",
    "section_title: 当前章节标题（可选）": "section_title: Current section title (optional)",
    "section_index: 当前章节索引（可选）": "section_index: Current section index (optional)",
    "追加写入 JSONL 文件": "Append to JSONL file",
    "记录报告生成开始": "Record report generation start",
    "\"message\": \"报告生成任务开始\"": "\"message\": \"Report generation task started\"",
    "记录大纲规划开始": "Record outline planning start",
    "\"message\": \"开始规划报告大纲\"": "\"message\": \"Starting to plan report outline\"",
    "记录规划时获取的上下文信息": "Record context info retrieved during planning",
    "\"message\": \"获取模拟上下文信息\"": "\"message\": \"Retrieved simulation context info\"",
    "记录大纲规划完成": "Record outline planning complete",
    "\"message\": \"大纲规划完成\"": "\"message\": \"Outline planning complete\"",
    "记录章节生成开始": "Record section generation start",
    "f\"开始生成章节: {section_title}\"": f"f\"Starting to generate section: {{section_title}}\"",
    "记录 ReACT 思考过程": "Record ReACT thinking process",
    "f\"ReACT 第{iteration}轮思考\"": f"f\"ReACT round {{iteration}} thinking\"",
    "记录工具调用": "Record tool call",
    "f\"调用工具: {tool_name}\"": f"f\"Calling tool: {{tool_name}}\"",
    "记录工具调用结果（完整内容，不截断）": "Record tool call result (full content, not truncated)",
    "f\"工具 {tool_name} 返回结果\"": f"f\"Tool {{tool_name}} returned results\"",
    "记录 LLM 响应（完整内容，不截断）": "Record LLM response (full content, not truncated)",
    "f\"LLM 响应 (工具调用: {has_tool_calls}, 最终答案: {has_final_answer})\"": f"f\"LLM response (tool calls: {{has_tool_calls}}, final answer: {{has_final_answer}})\"",
    "记录章节内容生成完成（仅记录内容，不代表整个章节完成）": "Record section content generation complete (content only, not entire section)",
    "f\"章节 {section_title} 内容生成完成\"": f"f\"Section {{section_title}} content generation complete\"",
    "记录章节生成完成": "Record section generation complete",
    "前端应监听此日志来判断一个章节是否真正完成，并获取完整内容": "Frontend should monitor this log to determine if a section is truly complete and get the full content.",
    "f\"章节 {section_title} 生成完成\"": f"f\"Section {{section_title}} generation complete\"",
    "记录报告生成完成": "Record report generation complete",
    "\"message\": \"报告生成完成\"": "\"message\": \"Report generation complete\"",
    "记录错误": "Record error",
    "f\"发生错误: {error_message}\"": f"f\"An error occurred: {{error_message}}\"",
    "Report Agent 控制台日志记录器": "Report Agent Console Logger",
    "将控制台风格的日志（INFO、WARNING等）写入报告文件夹中的 console_log.txt 文件。": "Write console-style logs (INFO, WARNING, etc.) into console_log.txt in the report folder.",
    "这些日志与 agent_log.jsonl 不同，是纯文本格式的控制台输出。": "These logs are different from agent_log.jsonl; they are plain text console output.",
    "初始化控制台日志记录器": "Initialize console logger",
    "设置文件处理器，将日志同时写入文件": "Set up file handler to write logs to file simultaneously",
    "使用与控制台相同的简洁格式": "Use the same concise format as the console",
    "添加到 report_agent 相关的 logger": "Add to report_agent related loggers",
    "避免重复添加": "Avoid duplicate additions",
    "关闭文件处理器并从 logger 中移除": "Close file handler and remove from loggers",
    "析构时确保关闭文件处理器": "Ensure file handler is closed upon destruction",
    "报告状态": "Report status",
    "报告章节": "Report section",
    "转换为Markdown格式": "Convert to Markdown format",
    "报告大纲": "Report outline",
    "报告摘要（一句话核心预测发现综述）": "Report summary (one-sentence overview of core prediction findings)",
    "章节内容描述": "Section content description",
    "完整报告": "Full report",
    "开始生成报告": "Starting report generation",
    "模拟需求": "Simulation requirement",
    "图谱ID": "Graph ID",
    "报告规划完成": "Report planning complete",
    "报告大纲:": "Report outline:",
    "开始生成第 {i+1}/{total} 章节: {section.title}": f"Starting generation of section {{i+1}}/{{total}}: {{section.title}}",
    "章节 {i+1} 生成完成": f"Section {{i+1}} generation complete",
    "所有章节生成通过，正在汇总报告内容...": "All sections generated successfully, consolidating report content...",
    "报告生成任务已完成": "Report generation task completed",
    "生成报告失败": "Failed to generate report",
    "开始规划报告大纲": "Starting to plan report outline",
    "正在进行大纲规划...": "Planning outline...",
    "规划完成": "Planning complete",
    "第几章节": "Section number",
    "正在生成内容...": "Generating content...",
    "失败重试中...": "Retry in progress...",
    "超过最大重试次数，尝试在不带历史记录的情况下重试": "Exceeded max retries, attempting to retry without history",
    "尝试最后一轮生成（不带ReACT）": "Attempting final generation round (without ReACT)",
    "获取章节证据": "Get section evidence",
    "正在检索章节证据映射...": "Retrieving section evidence mapping...",
    "证据映射已构建": "Evidence mapping built",
    "ReACT 第 {iteration} 轮迭代": f"ReACT iteration {{iteration}}",
    "LLM 思考:": "LLM Thinking:",
    "工具调用: {name}({params})": f"Tool call: {{name}}({{params}})",
    "工具返回长度: {len(result)}": f"Tool result length: {{len(result)}}",
    "收到最终答案": "Received final answer",
    "迭代超时，尝试提取已有内容": "Iteration timeout, attempting to extract existing content",
    "LLM 响应未包含工具调用或最终答案，视为异常": "LLM response contains no tool call or final answer, treating as exception",
    "正在生成最终答案...": "Generating final answer...",
    "Agent 对话开始": "Agent chat started",
    "正在模拟思考并搜寻事实...": "Simulating thinking and searching for facts...",
    "对话内容:": "Chat content:",
    "收到回复:": "Received reply:",
    "对话任务完成": "Chat task completed",
    "Agent 对话失败": "Agent chat failed",
    "构建对话上下文": "Build chat context",
    "【对话上下文】": "[Chat Context]",
    "用户正在询问关于该报告的问题。": "User is asking a question about this report.",
    "模拟需求: {self.simulation_requirement}": f"Simulation requirement: {{self.simulation_requirement}}",
    "图谱ID: {self.graph_id}": f"Graph ID: {{self.graph_id}}",
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(text)

print("done")
