import os

filepath = r"c:\Users\serge\OneDrive\Documents\GitHub\ASKTHEPEOPLE\backend\app\api\report.py"
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "Report API路由": "Report API Routes",
    "提供模拟报告生成、获取、对话等接口": "Provides interfaces for simulation report generation, retrieval, chat, etc.",
    "# ============== 报告生成接口 ==============": "# ============== Report Generation Interfaces ==============",
    "生成模拟分析报告（异步任务）": "Generate simulation analysis report (asynchronous task)",
    "这是一个耗时操作，接口会立即返回task_id，": "This is a time-consuming operation; the interface will immediately return a task_id.",
    "使用 GET /api/report/generate/status 查询进度": "Use GET /api/report/generate/status to check progress.",
    "请求（JSON）：": "Request (JSON):",
    "// 必填，模拟ID": "// Required, simulation ID",
    "// 可选，强制重新生成": "// Optional, force regeneration",
    "返回：": "Returns:",
    "\"message\": \"报告生成任务已启动\"": "\"message\": \"Report generation task started\"",
    "\"error\": \"请提供 simulation_id\"": "\"error\": \"Please provide simulation_id\"",
    "获取模拟信息": "Get simulation info",
    "f\"模拟不存在: {simulation_id}\"": "f\"Simulation does not exist: {simulation_id}\"",
    "检查是否已有报告": "Check if report already exists",
    "\"message\": \"报告已存在\"": "\"message\": \"Report already exists\"",
    "获取项目信息": "Get project info",
    "f\"项目不存在: {state.project_id}\"": "f\"Project does not exist: {state.project_id}\"",
    "\"error\": \"缺少图谱ID，请确保已构建图谱\"": "\"error\": \"Missing graph ID, please ensure the graph is built\"",
    "\"error\": \"缺少模拟需求描述\"": "\"error\": \"Missing simulation requirement description\"",
    "提前生成 report_id，以便立即返回给前端": "Pre-generate report_id to return to the frontend immediately",
    "创建异步任务": "Create asynchronous task",
    "定义后台任务": "Define background task",
    "message=\"初始化Report Agent...\"": "message=\"Initializing Report Agent...\"",
    "创建Report Agent": "Create Report Agent",
    "进度回调": "Progress callback",
    "生成报告（传入预先生成的 report_id）": "Generate report (passing pre-generated report_id)",
    "保存报告": "Save report",
    "\"报告生成失败\"": "\"Report generation failed\"",
    "报告生成失败: ": "Report generation failed: ",
    "启动后台线程": "Start background thread",
    "报告生成任务已启动，请通过 /api/report/generate/status 查询进度": "Report generation task started, please check progress via /api/report/generate/status",
    "启动报告生成任务失败: ": "Failed to start report generation task: ",
    "查询报告生成任务进度": "Query report generation task progress",
    "// 可选，generate返回的task_id": "// Optional, task_id returned by generate",
    "// 可选，模拟ID": "// Optional, simulation ID",
    "\"message\": (progress or {}).get(\"message\") or (\"报告已生成\" if report.status == ReportStatus.COMPLETED else \"报告处理中\"),": "\"message\": (progress or {}).get(\"message\") or (\"Report generated\" if report.status == ReportStatus.COMPLETED else \"Report processing\"),",
    "\"报告处理中\"": "\"Report processing\"",
    "如果提供了simulation_id，先检查是否已有完成的报告": "If simulation_id is provided, check for an existing completed report first",
    "\"message\": \"报告已生成\"": "\"message\": \"Report generated\"",
    "\"error\": \"请提供 task_id、simulation_id 或 report_id\"": "\"error\": \"Please provide task_id, simulation_id, or report_id\"",
    "f\"任务不存在: {task_id}\"": "f\"Task does not exist: {task_id}\"",
    "查询任务状态失败: ": "Failed to query task status: ",
    "# ============== 报告获取接口 ==============": "# ============== Report Retrieval Interfaces ==============",
    "获取报告章节证据映射": "Get report section evidence mapping",
    "f\"报告不存在: {report_id}\"": "f\"Report does not exist: {report_id}\"",
    "获取报告证据失败: ": "Failed to get report evidence: ",
    "获取报告详情": "Get report details",
    "根据模拟ID获取报告": "Get report by simulation ID",
    "f\"该模拟暂无报告: {simulation_id}\"": "f\"No report found for this simulation: {simulation_id}\"",
    "获取报告失败: ": "Failed to get report: ",
    "列出所有报告": "List all reports",
    "Query参数：": "Query parameters:",
    "按模拟ID过滤（可选）": "Filter by simulation ID (optional)",
    "返回数量限制（默认50）": "Return quantity limit (default 50)",
    "列出报告失败: ": "Failed to list reports: ",
    "下载报告（Markdown格式）": "Download report (Markdown format)",
    "返回Markdown文件": "Return Markdown file",
    "如果MD文件不存在，生成一个临时文件": "If the MD file doesn't exist, generate a temporary file",
    "下载报告失败: ": "Failed to download report: ",
    "\"删除报告\"": "\"Delete report\"",
    "\"报告已删除: {report_id}\"": "\"Report deleted: {report_id}\"",
    "删除报告失败: ": "Failed to delete report: ",
    "# ============== Report Agent对话接口 ==============": "# ============== Report Agent Chat Interfaces ==============",
    "与Report Agent对话": "Chat with Report Agent",
    "Report Agent可以在对话中自主调用检索工具来回答问题": "Report Agent can autonomously call retrieval tools during chat to answer questions",
    "// 必填，模拟ID": "// Required, simulation ID",
    "\"message\": \"请解释一下舆情走向\",    // 必填，用户消息": "\"message\": \"Please explain the public opinion trend\",    // Required, user message",
    "// 可选，对话历史": "// Optional, chat history",
    "\"response\": \"Agent回复...\",": "\"response\": \"Agent reply...\",",
    "\"tool_calls\": [调用的工具列表],": "\"tool_calls\": [List of called tools],",
    "\"sources\": [信息来源]": "\"sources\": [Information sources]",
    "\"error\": \"请提供 message\"": "\"error\": \"Please provide message\"",
    "获取模拟和项目信息": "Get simulation and project info",
    "\"error\": \"缺少图谱ID\"": "\"error\": \"Missing graph ID\"",
    "创建Agent并进行对话": "Create Agent and start chat",
    "对话失败: ": "Chat failed: ",
    "# ============== 报告进度与分章节接口 ==============": "# ============== Report Progress and Section Interfaces ==============",
    "获取报告生成进度（实时）": "Get report generation progress (real-time)",
    "\"正在生成章节: 关键发现\"": "\"Generating section: Key Findings\"",
    "\"current_section\": \"关键发现\"": "\"current_section\": \"Key Findings\"",
    "\"completed_sections\": [\"执行摘要\", \"模拟背景\"]": "\"completed_sections\": [\"Executive Summary\", \"Simulation Background\"]",
    "f\"报告不存在或进度信息不可用: {report_id}\"": "f\"Report does not exist or progress info is unavailable: {report_id}\"",
    "获取报告进度失败: ": "Failed to get report progress: ",
    "获取已生成的章节列表（分章节输出）": "Get generated section list (sectioned output)",
    "前端可以轮询此接口获取已生成的章节内容，无需等待整个报告完成": "Frontend can poll this interface to get generated section content without waiting for the full report to complete",
    "\"content\": \"## 执行摘要\\\\n\\\\n...\"": "\"content\": \"## Executive Summary\\\\n\\\\n...\"",
    "获取报告状态": "Get report status",
    "获取章节列表失败: ": "Failed to get section list: ",
    "获取单个章节内容": "Get single section content",
    "f\"章节不存在: section_{section_index:02d}.md\"": "f\"Section does not exist: section_{section_index:02d}.md\"",
    "获取章节内容失败: ": "Failed to get section content: ",
    "# ============== 报告状态检查接口 ==============": "# ============== Report Status Check Interfaces ==============",
    "检查模拟是否有报告，以及报告状态": "Check if simulation has a report and its status",
    "用于前端判断是否解锁Interview功能": "Used for frontend to determine whether to unlock Interview function",
    "只有报告完成后才解锁interview": "Unlock interview only after report is completed",
    "检查报告状态失败: ": "Failed to check report status: ",
    "# ============== Agent 日志接口 ==============": "# ============== Agent Log Interfaces ==============",
    "获取 Report Agent 的详细执行日志": "Get detailed execution logs of Report Agent",
    "实时获取报告生成过程中的每一步动作，包括：": "Get every action in the report generation process in real-time, including:",
    "- 报告开始、规划开始/完成": "- Report start, planning start/completion",
    "- 每个章节的开始、工具调用、LLM响应、完成": "- Each section start, tool call, LLM response, completion",
    "- 报告完成或失败": "- Report completion or failure",
    "从第几行开始读取（可选，默认0，用于增量获取）": "Read from which line (optional, default 0, for incremental retrieval)",
    "\"section_title\": \"执行摘要\",": "\"section_title\": \"Executive Summary\",",
    "获取Agent日志失败: ": "Failed to get Agent log: ",
    "获取完整的 Agent 日志（一次性获取全部）": "Get complete Agent logs (retrieve all at once)",
    "# ============== 控制台日志接口 ==============": "# ============== Console Log Interfaces ==============",
    "获取 Report Agent 的控制台输出日志": "Get console output logs of Report Agent",
    "实时获取报告生成过程中的控制台输出（INFO、WARNING等），": "Get console output (INFO, WARNING, etc.) during report generation in real-time.",
    "这与 agent-log 接口返回的结构化 JSON 日志不同，": "This is different from the structured JSON logs returned by the agent-log interface,",
    "是纯文本格式的控制台风格日志。": "it's plain text console-style logs.",
    "\"搜索完成: 找到 15 条相关事实\"": "\"Search complete: Found 15 relevant facts\"",
    "\"图谱搜索: graph_id=xxx, query=...\"": "\"Graph search: graph_id=xxx, query=...\"",
    "获取控制台日志失败: ": "Failed to get console log: ",
    "获取完整的控制台日志（一次性获取全部）": "Get complete console logs (retrieve all at once)",
    "# ============== 工具调用接口（供调试使用）==============": "# ============== Tool Call Interfaces (for debugging) ==============",
    "图谱搜索工具接口（供调试使用）": "Graph search tool interface (for debugging)",
    "\"query\": \"搜索查询\"": "\"query\": \"Search query\"",
    "\"error\": \"请提供 graph_id 和 query\"": "\"error\": \"Please provide graph_id and query\"",
    "图谱搜索失败: ": "Graph search failed: ",
    "图谱统计工具接口（供调试使用）": "Graph statistics tool interface (for debugging)",
    "\"error\": \"请提供 graph_id\"": "\"error\": \"Please provide graph_id\"",
    "获取图谱统计失败: ": "Failed to get graph statistics: ",
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(text)

print("done")
