"""Initial schema

Revision ID: 384c98f88d53
Revises: 
Create Date: 2026-08-02 20:47:03.023904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384c98f88d53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('total_text_length', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('simulation_requirement', sa.Text(), nullable=True),
    sa.Column('graph_id', sa.String(length=64), nullable=True),
    sa.Column('graph_build_task_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_table('graphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('graph_id', sa.String(length=64), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphs_graph_id'), 'graphs', ['graph_id'], unique=True)
    op.create_index('ix_graphs_project_id', 'graphs', ['project_id'], unique=False)
    op.create_index('ix_graphs_status', 'graphs', ['status'], unique=False)
    op.create_table('ontologies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ontologies_project_id', 'ontologies', ['project_id'], unique=False)
    op.create_index('ix_ontologies_status', 'ontologies', ['status'], unique=False)
    op.create_index(op.f('ix_ontologies_task_id'), 'ontologies', ['task_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulations_created_at', 'simulations', ['created_at'], unique=False)
    op.create_index('ix_simulations_project_id', 'simulations', ['project_id'], unique=False)
    op.create_index(op.f('ix_simulations_simulation_id'), 'simulations', ['simulation_id'], unique=True)
    op.create_index('ix_simulations_status', 'simulations', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_content_hash'), 'sources', ['content_hash'], unique=False)
    op.create_index('ix_sources_project_id', 'sources', ['project_id'], unique=False)
    op.create_index('ix_sources_upload_date', 'sources', ['upload_date'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('export_format', sa.String(length=20), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_format', 'reports', ['export_format'], unique=False)
    op.create_index('ix_reports_generated_at', 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=True)
    op.create_index('ix_reports_simulation_id', 'reports', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_simulation_id', table_name='reports')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index('ix_reports_generated_at', table_name='reports')
    op.drop_index('ix_reports_format', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_sources_upload_date', table_name='sources')
    op.drop_index('ix_sources_project_id', table_name='sources')
    op.drop_index(op.f('ix_sources_content_hash'), table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_simulations_status', table_name='simulations')
    op.drop_index(op.f('ix_simulations_simulation_id'), table_name='simulations')
    op.drop_index('ix_simulations_project_id', table_name='simulations')
    op.drop_index('ix_simulations_created_at', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_ontologies_task_id'), table_name='ontologies')
    op.drop_index('ix_ontologies_status', table_name='ontologies')
    op.drop_index('ix_ontologies_project_id', table_name='ontologies')
    op.drop_table('ontologies')
    op.drop_index('ix_graphs_status', table_name='graphs')
    op.drop_index('ix_graphs_project_id', table_name='graphs')
    op.drop_index(op.f('ix_graphs_graph_id'), table_name='graphs')
    op.drop_table('graphs')
    op.drop_index('ix_projects_user_status', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index('ix_projects_created_at', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
